### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by vlahde** [OPMerchantServices/op-payment-service-php-sdk#13]
I simple instruction of SDK usage would be nice. How to build a payment request?

**Comment by traone** [comment]
Hi,
thanks for your input. 

Simple examples are on their way. We are about to ship out a new release very shortly. Also a PHPUnit test suite will be included with the release, which will also have examples for creating a payment request, payment status request etc.

**Comment by vlahde** [comment]
Okay thanks,

How shortly is that approx.? I mean should I just wait for it or proceed without?

**Comment by villesiltala** [comment]
@vlahde, thanks for your interest! The examples are developed in the [readme](https://github.com/OPMerchantServices/op-payment-service-php-sdk/tree/readme) branch. Not much there yet, but this issue will be updated once the examples are ready.

If you are familiar with WordPress and WooCommerce, you can take a look at how the official WooCommerce payment gateway plugin handles the payment and refund processes with this SDK:
https://github.com/OPMerchantServices/op-payment-service-for-woocommerce

**Comment by traone** [comment]
> Okay thanks,
> 
> How shortly is that approx.? I mean should I just wait for it or proceed without?

@vlahde New release has just been shipped out. 

For an example how to create a payment request, please have a look at [ClientTest.php](https://github.com/OPMerchantServices/op-payment-service-php-sdk/blob/master/tests/unit/ClientTest.php) and it should get you started.

**Comment by vlahde** [comment]
Thanks I tried that out and using that as a base, I can pass the validation but doing the request will result in 400 bad request error. Am I missing something?

`
        $client = new Client(config('billing.CO_merchantId'), config('billing.CO_merchantSecret'));

        $r = new PaymentRequest();
        $r->setAmount(1000);
        $r->setStamp(time());
        $r->setReference('RequestReference123'.time());
        $r->setCurrency('EUR');
        $r->setLanguage('FI');

        $item1 = new Item();
        $item1->setStamp(time())
            ->setDeliveryDate(date('Y.m.d'))
            ->setProductCode('pr1')
            ->setVatPercentage(25)
            ->setUnitPrice(1000)
            ->setDescription('credio')
            ->setUnits(1);
        $r->setItems([$item1]);

        $c = new Customer();
        $c->setEmail('customer@email.com');
        $r->setCustomer($c);

        $cb = new CallbackUrl();
        $cb->setCancel('https://somedomain.com/cancel')
            ->setSuccess('https://somedomain.com/success');
        $r->setCallbackUrls($cb);
        $redirect = new CallbackUrl();
        $redirect->setSuccess('https://someother.com/success')
            ->setCancel('https://someother.com/cancel');
        $r->setRedirectUrls($redirect);

        try {
            $r->validate();
        } catch (ValidationException $e) {
        }

        //this will fail
        return response($client->createPayment($r));
`

**Comment by vlahde** [comment]
POST https://api.checkout.fi/payments` resulted in a `400 Bad Request` response: {"status":"error","message":"Request payload schema validation failed. Validate request against the provided schema."

**Comment by loueranta** [comment]
@vlahde  Please provide me the request ID and I'll check the logs on our end

**Comment by vlahde** [comment]
Got this working already thanks.
