### ISSUE TITLE
getPaymentStatus documentation for return differs from actual return type

### ISSUE THREAD

**Issue by niklasmannila** [OPMerchantServices/op-payment-service-php-sdk#14]
**Describe the bug**

The return type of _getPaymentStatus_ inside Client.php is wrong. The function documentation states that it will return a _PaymentResponse_ but it actually returns a _PaymentStatusResponse_.
If you need to check the status for that response, for example the IDE will show a:
`Method 'getStatus' not found in OpMerchantServices\SDK\Response\PaymentResponse`.

**To Reproduce**
Create a new checkout payment, grab the transaction id and get the payment status using the transaction id. Call 'getStatus' for the response object.

**Expected behavior**
Function documentation should match what the function returns. So it should be documented to return a 'PaymentStatusResponse' instead of 'PaymentResponse'.

**Comment by traone** [comment]
Hi,
thanks for reporting this. 

I have created a fix this in a development branch, and it will be released on the next upcoming release.
