### ISSUE TITLE
vatPercentage is not an integer for zero vat items

### ISSUE THREAD

**Issue by niklasmannila** [OPMerchantServices/op-payment-service-php-sdk#17]
**Describe the bug**
Validation fails for zero vat percentage items in version 1.0.2. 

**To Reproduce**

1. Create an item and set the vatpercentage as zero
2. Create payment and set the item for the payment
3. Validation fails with 'vatPercentage is not an integer'

**Expected behavior**
Zero vat percentage should be valid since this is very common, especially when selling gift cards or other zero vat percentage products.

Item validation for integer is:
`
if (!filter_var($props['vatPercentage'], FILTER_VALIDATE_INT)) {
    throw new ValidationException('vatPercentage is not an integer');
}`
but it probably should be:
`
if (filter_var($props['vatPercentage'], FILTER_VALIDATE_INT) === false) {
    throw new ValidationException('vatPercentage is not an integer');
}`
since the filter_var function will return int 0, which is interpreted as falsy if not comparing it correctly.

**Additional context**
This issue did not occur in version 1.0.1 but it did occur previously at some point and then it was fixed. Now it is broken again. We were forced to revert to version 1.0.1 until you get this fixed.

You should maybe consider adding this test scenario to your unit test for items. Maybe it would prevent this from occurring again later on?

**Comment by traone** [comment]
Hi @niklasmannila and thanks for the bug report.

You are correct, and I have amended a fix for the upcoming release, which will be published next week, most likely Monday or Tuesday.

Unfortunately this slipped through our test suite, as we weren't comparing the return value in a strict manner, as you pointed out. I will improve the validation comparisons.

Thanks again for reporting this. Stay tuned for the upcoming release.

**Comment by niklasmannila** [comment]
Good to hear! I am subscribing to your releases and I will make sure we get back on the latest version when this issue is fixed!
