### ISSUE TITLE
Client error: `POST https://api.checkout.fi/payments` resulted in a `400 Bad Request`

### ISSUE THREAD

**Issue by MiesSuomesta** [OPMerchantServices/op-payment-service-php-sdk#34]
**Describe your question**

I get when trying with the test-merchant "Client error: `POST https://api.checkout.fi/payments` resulted in a `400 Bad Request` response:
{"status":"error","message":"Request payload schema validation failed. Validate request against the provided schema."

How to fix ? .. validation goes OK...

Code:

	$pr = new \OpMerchantServices\SDK\Request\PaymentRequest();
	$pr->setAmount($total_price_without_vat_in_cents);
        $pr->setStamp($stamp);
        $pr->setReference($orderid);
        $pr->setCurrency('EUR');

	if ($_SESSION['kieli'] == "fi")
		$pr->setLanguage('FI');
	else
		$pr->setLanguage('EN');

	echo "<center>
		<br><br><br><br>
		<h1>$title_confirm_bank_wait<h1>
		<br><br><br><br>
		<table>";
	echo "<tr><td width='50%'>$label_product<td><td width='30%' align='right'>$label_price<td></tr>";
	$i = 1;
	$tot = 0;
	foreach($items as $itm)
	{
		$prc = $itm->getProductCode();
		$vat = $itm->getVatPercentage();
		$val = $itm->getUnitPrice() / 100;

		$tot += $val;

		echo "<tr> <td width='50%'>$prc<td> <td width='30%' align='right'>$val EUR<td> </tr>";

		$i++;
	}
		$i--;

	if ($_SESSION['kieli'] == "fi")
		echo "<tr><td>$i tuotetta<td><td align='right'>$tot EUR<td></tr>";
	else
		echo "<tr><td>$i items<td><td align='right'>$tot EUR<td></tr>";

	echo "</table></center>";

	$pr->setItems($items);

	$c = new \OpMerchantServices\SDK\Model\Customer();
        $c->setEmail($clientemail);

        $pr->setCustomer($c);

	$redirect = new \OpMerchantServices\SDK\Model\CallbackUrl();
	$redirect->setSuccess('https://paxsudos.com/op/success.php')
		 ->setCancel('https://paxsudos.com/op/cancel.php');

	$pr->setRedirectUrls($redirect);

	if (! $pr->validate())
	{
		echo "<br><br><br><h1>Validation error!</h1><br><br><br>";
		vardump($pr);
	} else {
		echo "<center>Validation ok...</center>";
	}

	$providers_per_row = 4;
	$providers_name_colspan = $providers_per_row - 1;
	$providers_not_done = $providers_per_row;
	$group_icon_size_by_size=40;

	try {

		$resp = op_createPayment($pr);

	} catch (HmacException $e) {
		echo "<br><br><br><h1>Response error!</h1><br><br><br><h1>";
		vardump($e->getMessage());
	} catch (ValidationException $e) {
		echo "<br><br><br><h1>Response error!</h1><br><br><br><h1>";
		vardump($e->getMessage());
	} catch (RequestException $e) {
		echo "<br><br><br><h1>Response error!</h1><br><br><br><h1>";
		vardump(json_decode($e->getResponse()->getBody()));
	} catch (Exception $e) {
		echo "<br><br><br><h1>Response error!</h1><br><br><br><h1>";
		vardump($e);
	}

**Comment by MiesSuomesta** [comment]
headerit ---------------------------------------------
array(8) {
  ["checkout-account"]=>
  int(375917)
  ["checkout-algorithm"]=>
  string(6) "sha256"
  ["checkout-method"]=>
  string(4) "POST"
  ["checkout-nonce"]=>
  string(14) "15f36d3237e986"
  ["checkout-timestamp"]=>
  string(27) "2020-08-14T21:08:35.518528Z"
  ["cof-plugin-version"]=>
  string(18) "paxsudos-com-1.0.0"
  ["content-type"]=>
  string(31) "application/json; charset=utf-8"
  ["signature"]=>
  string(64) "a00d53a7ce03193c0175592554757f1f9e2b0df05633780b95866584cb4e8090"
}
headerit ---------------------------------------------

		

body ---------------------------------------------
string(857) "{"stamp":"InformationBrick-9c36ef948dfe00a5d68be26bdd27a623","reference":"9c36ef948dfe00a5d68be26bdd27a623","amount":26000,"currency":"EUR","language":"EN","items":[{"unitPrice":17000,"units":1,"vatPercentage":24,"productCode":"informationbrick: NUC kit","deliveryDate":"28.08.2020","stamp":"IB-9c36ef948dfe00a5d68be26bdd27a623"},{"unitPrice":5000,"units":1,"vatPercentage":24,"productCode":"IB: memory 4GB","deliveryDate":"28.08.2020","stamp":"IB-9c36ef948dfe00a5d68be26bdd27a623"},{"unitPrice":4000,"units":1,"vatPercentage":24,"productCode":"IB: SSD 120GB","deliveryDate":"28.08.2020","stamp":"IB-9c36ef948dfe00a5d68be26bdd27a623"}],"customer":{"email":"tero@joku.com"},"redirectUrls":{"success":"https://joku.com/op/success.php","cancel":"https://joku.com/op/cancel.php"}}"
body ---------------------------------------------

printit protected function post ( op-merchant-services/op-payment-service-php-sdk/src/Client.php ssa )

**Comment by loueranta** [comment]
I checked the logs on our end and it seems that the `deliveryDate` is in wrong format:

`{u'status': u'error', u'message': u'Request payload schema validation failed. Validate request against the provided schema.', u'meta': [u'instance.items[0].deliveryDate does not conform to the "YYYY-MM-DD" format', u'instance.items[1].deliveryDate does not conform to the "YYYY-MM-DD" format', u'instance.items[2].deliveryDate does not conform to the "YYYY-MM-DD" format']} `

**Comment by MiesSuomesta** [comment]
headerit ---------------------------------------------
array(9) {
  ["checkout-account"]=>
  int(826654)
  ["checkout-algorithm"]=>
  string(6) "sha256"
  ["checkout-method"]=>
  string(4) "POST"
  ["checkout-nonce"]=>
  string(14) "15f3f5cc02d8fe"
  ["checkout-timestamp"]=>
  string(27) "2020-08-21T08:33:52.186617Z"
  ["cof-plugin-version"]=>
  string(18) "paxsudos-com-1.0.0"
  ["content-type"]=>
  string(31) "application/json; charset=utf-8"
  ["checkout-provider"]=>
  string(10) "creditcard"
  ["signature"]=>
  string(64) "5f80d7606e48a4585f677377ddfd3ff057b3c706b5680198913d0dc69d458fd3"
}
headerit ---------------------------------------------

		

		body ---------------------------------------------
string(913) "{"stamp":"InformationBrick-4e76b6f7264d135035329f2cf524dbc9-5f3f5cc02d75b","reference":"4e76b6f7264d135035329f2cf524dbc9","amount":26000,"currency":"EUR","language":"FI","items":[{"unitPrice":17000,"units":1,"vatPercentage":24,"productCode":"informationbrick: NUC kit","deliveryDate":"2020-09-04","stamp":"InformationBrick-4e76b6f7264d135035329f2cf524dbc9-5f3f5cc02d75b"},{"unitPrice":5000,"units":1,"vatPercentage":24,"productCode":"informationbrick: memory 4GB","deliveryDate":"2020-09-04","stamp":"InformationBrick-4e76b6f7264d135035329f2cf524dbc9-5f3f5cc02d75b"},{"unitPrice":4000,"units":1,"vatPercentage":24,"productCode":"informationbrick: SSD 120GB","deliveryDate":"2020-09-04","stamp":"InformationBrick-4e76b6f7264d135035329f2cf524dbc9-5f3f5cc02d75b"}],"customer":{"email":"lja@paxsudos.com"},"redirectUrls":{"success":"https://paxsudos.com/op/success.php","cancel":"https://paxsudos.com/op/cancel.php"}}"
body ---------------------------------------------

.. cant pay with VISA or with OP


  ["checkout-provider"]=>
  string(10) "creditcard"

Tuon headerin lisäsin itse, kun oli vissiin unohtunut.. tuon kanssa tai ilman, ei pelaa

**Comment by MiesSuomesta** [comment]
![image](https://user-images.githubusercontent.com/32951624/90857786-8afdbc80-e38d-11ea-9e8a-23f218778e6b.png)

tulee jos koettaa OP:n kautta tehdä tilauksen oikeilla credeillä

**Comment by loueranta** [comment]
Hei, yrität ilmeisesti luoda maksutapahtuman suoraan ensimmäisessä requestissa, joka ei ole oikea tapa luoda maksutapahtumia. 

Sinun tulee ensin alustaa maksutapahtuma ja vasta sen jälkeen valita maksutapa tai ohjata asiakas meidän maksuseinälle.

Suosittelen siis perehtymään tarkemmin rajapintadokumentaatioon: https://checkoutfinland.github.io/psp-api/#/?id=payments

**Comment by MiesSuomesta** [comment]
Joo, ongelma oli siinä, koodissa myös oli huomioitava: emaili ei saa olla tyhjä, ja amount on tosiaan euro-sentteinä ja jokaselle kaupattavalle oma iteminsä.
