### ISSUE TITLE
Description is required for items

### ISSUE THREAD

**Issue by niklasmannila** [OPMerchantServices/op-payment-service-php-sdk#6]
Item validation fails if the description is not set. According to the Checkout Finland documentation it should not be a required attribute. Either the documentation is wrong or then it shouldn't require it to be set. Setting it as null won't work since the validate function does a stringType() validation on the value.

**Comment by loueranta** [comment]
Thanks for reporting. I'll investigate and get back to you.

**Comment by loueranta** [comment]
You were right, the validation is unnecessary. We will fix this in the next release.

**Comment by niklasmannila** [comment]
Awesome, thank you!
