### ISSUE TITLE
how to set up Shop-in-Shop client?

### ISSUE THREAD

**Issue by nabeelzqadri** [OPMerchantServices/op-payment-service-php-sdk#7]
in this can only pass merchant id and secret there is no information how to pass shop-in-shop merchant id?
`Shop-in-Shop merchant account
Note: Use these only if you are setting up a Shop-in-Shop web shop.

Aggregate merchant ID: *****
Aggregate secret key: *****
Shop-in-Shop merchant ID: 695874
`

**Comment by loueranta** [comment]
@nabeelzqadri Sorry, but the current version of the PHP-SDK doesn't support Shop-in-Shop scenarios.

**Comment by nabeelzqadri** [comment]
No worries
Thank you
