### ISSUE TITLE
Setting 'cofPluginVersion' should be done automatically

### ISSUE THREAD

**Issue by niklasmannila** [OPMerchantServices/op-payment-service-php-sdk#9]
I have been notified that you would appreciate setting the 'cofPluginVersion' so that you can track the requests and see what version of the plugin is being used.
But wouldn't it be easier to have the correct version set as default in the Client.php file. Otherwise you are relying on people remembering to update the version where the Client constructor is being called. If the package itself would include it and pass it along it would be easier for those who use the sdk and also it would contain a little bit more reliable version information since you are not depending on us to make sure it is up to date. 
Also a follow-up question, am I correct in thinking that the 'cofPluginVersion' is the version specified in the generated composer.lock file?

**Comment by traone** [comment]
Hi there.

As some parties use this library to create their own implementations to interact with the Checkout API, for statistics and support cases it is better to have a unique version for each implementation to keep better tracks of things. That being said, if each implementation would just use the fallback value, then debugging / helping out customers will be a bit more troublesome. With the implementation specific version identifiers this becomes a lot easier.

For SaaS services, use the marketing name of the platform. For eCommerce platform plugins, use the platform name, your identifier, and plugin version (for example, woocommerce-yourcompany-1.1.0). Platform information helps customer service to provide better assistance for the merchants using the plugin.

For the follow up question: No it's not. As explained above, the version should reflect the service that is using the library.

In the upcoming release the version identifier will be a mandatory parameter to the Client instance constructor.

**Comment by niklasmannila** [comment]
Okay! Now I think I get it. Probably in our case when we are using the SDK without any specific ready plugin we should just set the plugin cofPluginVersion as '[ourmarketingname]-1.0'. I get that this will make it easier for customer service to assist when being able to match requests to the correct version.

Thank you for clearing this up!
